SELECT FIRST_NAME AS "<WORKER_NAME>"
FROM WORKERS;

SELECT UPPER(FIRST_NAME) AS UPPER_FIRST_NAME
FROM WORKERS;

SELECT SUBSTR(FIRST_NAME, 1, 3) AS FIRST_THREE_CHARACTERS
FROM WORKERS;

--Names with a
SELECT FIRST_NAME WHERE FIRST_NAME LIKE 'A%'
AS NAMES_WITH_A
FROM WORKERS;

SELECT RTRIM(first_name) AS trimmed_first_name
FROM WORKERS;
