SELECT FIRST_NAME AS "<WORKER_NAME>"
FROM WORKERS;

SELECT UPPER(FIRST_NAME) AS UPPER_FIRST_NAME
FROM WORKERS;

SELECT SUBSTR(FIRST_NAME, 1, 3) AS FIRST_THREE_CHARACTERS
FROM WORKERS;

--Names with a
SELECT FIRST_NAME AS NAMES_WITH_A
FROM WORKERS
WHERE FIRST_NAME LIKE 'A%';

SELECT RTRIM(first_name) AS trimmed_first_name
FROM WORKERS;

SELECT RTRIM(DEPARTMENT) AS trimmed_dept 
FROM WORKERS;

SELECT DISTINCT RTRIM(DEPARTMENT) AS distinct_trimmed_dept 
FROM WORKERS;

SELECT DISTINCT RTRIM(DEPARTMENT), LENGTH(DEPARTMENT) AS distinct_trimmed_dept
FROM WORKERS;