CREATE VIEW WorkerView AS
SELECT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY
FROM WORKERS;

INSERT INTO WorkerView (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY)
VALUES (4, 'Eva', 'Johnson', 58000.00);


UPDATE WorkerView
SET SALARY = 60000.00
WHERE WORKER_ID = 3;
